version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile-web
    ports:
      - 80:80
    depends_on:
      - db
      - inmem
      - app
    volumes:
      - web-data:/app/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appli
    depends_on:
      - inmem
      - app
    volumes:
      - db-data:/var/lib/postgresql/data

  inmem:
    image: redis:latest
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: dockerfile-app
    volumes:
      - app-data:/app/data

volumes:
  web-data:
  db-data:
  redis-data:
  app-data:

